import './globals.css'

export const metadata = {
  title: 'Tasks management',
  description: 'Generated by Skillrazr',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-[#F5F6F8]'>{children}</body>
    </html>
  )
}
